// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXrL5Dd2FVdi2ENEvlFJcYpCrRchGDg48',
    appId: '1:377907540070:web:6ca7a79e601bc6dcd2bda7',
    messagingSenderId: '377907540070',
    projectId: 'ai-report-6c914',
    authDomain: 'ai-report-6c914.firebaseapp.com',
    storageBucket: 'ai-report-6c914.firebasestorage.app',
    measurementId: 'G-FZFWBVNJ95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAldftMzXW3p3T8Y4WWPku1E1FVgwytwXo',
    appId: '1:377907540070:android:c84e93b51d692634d2bda7',
    messagingSenderId: '377907540070',
    projectId: 'ai-report-6c914',
    storageBucket: 'ai-report-6c914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnHxpeYI9bofIaI0XgJ5Yl8nZthiiG_k8',
    appId: '1:377907540070:ios:e65b4f76f5c498c3d2bda7',
    messagingSenderId: '377907540070',
    projectId: 'ai-report-6c914',
    storageBucket: 'ai-report-6c914.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnHxpeYI9bofIaI0XgJ5Yl8nZthiiG_k8',
    appId: '1:377907540070:ios:e65b4f76f5c498c3d2bda7',
    messagingSenderId: '377907540070',
    projectId: 'ai-report-6c914',
    storageBucket: 'ai-report-6c914.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXrL5Dd2FVdi2ENEvlFJcYpCrRchGDg48',
    appId: '1:377907540070:web:c4c30bdaefa39e80d2bda7',
    messagingSenderId: '377907540070',
    projectId: 'ai-report-6c914',
    authDomain: 'ai-report-6c914.firebaseapp.com',
    storageBucket: 'ai-report-6c914.firebasestorage.app',
    measurementId: 'G-MPLXHSRRZ0',
  );
}
