import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:intl/intl.dart';

class ReportDetailScreen extends StatelessWidget {
  final Map<String, dynamic> reportData;

  const ReportDetailScreen({super.key, required this.reportData});

  // --- HELPER: FETCH DOCTOR NAME ---
  // Ye function doctor ki ID se uska naam dhoond kar layega
  Future<String> _fetchDoctorName(String? doctorId) async {
    if (doctorId == null || doctorId.isEmpty) return "Unknown";

    try {
      // 1. Check 'doctors' collection
      DocumentSnapshot doc = await FirebaseFirestore.instance.collection('doctors').doc(doctorId).get();
      if (doc.exists) return doc['name'] ?? "Unknown";

      // 2. Fallback: Check 'users' collection (Old data)
      doc = await FirebaseFirestore.instance.collection('users').doc(doctorId).get();
      if (doc.exists) return doc['name'] ?? "Unknown";

    } catch (e) {
      return "Error";
    }
    return "Unknown";
  }

  @override
  Widget build(BuildContext context) {
    // --- DATE FORMATTING ---
    String formattedDate = "Unknown Date";
    if (reportData['date'] != null) {
      Timestamp t = reportData['date'];
      DateTime d = t.toDate();
      formattedDate = DateFormat('dd-MM-yyyy at h:mm a').format(d);
    }

    // Get Doctor ID from report data
    String doctorId = reportData['doctorId'] ?? "";

    return Scaffold(
      backgroundColor: const Color(0xFFF2F2F7),
      appBar: AppBar(
        title: const Text("Medical Report Details", style: TextStyle(color: Colors.black)),
        backgroundColor: Colors.white,
        elevation: 0,
        iconTheme: const IconThemeData(color: Colors.black),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // --- MAIN INFO CARD ---
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(16),
                boxShadow: [BoxShadow(color: Colors.black12, blurRadius: 5)],
              ),
              child: Column(
                children: [
                  // --- SECTION 1: PATIENT INFO ---
                  const Align(
                    alignment: Alignment.centerLeft,
                    child: Text("PATIENT DETAILS", style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Colors.grey)),
                  ),
                  const SizedBox(height: 10),
                  _detailRow(Icons.person, "Name", reportData['patientName'] ?? 'N/A'),
                  const SizedBox(height: 8),
                  _detailRow(Icons.badge, "Patient ID", reportData['patientId'] ?? 'N/A'),

                  const Divider(height: 30),

                  // --- SECTION 2: REPORT INFO ---
                  const Align(
                    alignment: Alignment.centerLeft,
                    child: Text("REPORT INFO", style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Colors.grey)),
                  ),
                  const SizedBox(height: 10),
                  _detailRow(Icons.calendar_today, "Date", formattedDate),
                  const SizedBox(height: 8),
                  _detailRow(Icons.local_hospital, "Status", reportData['status'] ?? 'Completed', isStatus: true),

                  // --- SECTION 3: DOCTOR INFO (NEW UPDATE) ---
                  if (doctorId.isNotEmpty) ...[
                    const Divider(height: 30),
                    const Align(
                      alignment: Alignment.centerLeft,
                      child: Text("GENERATED BY", style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Colors.grey)),
                    ),
                    const SizedBox(height: 10),

                    FutureBuilder<String>(
                      future: _fetchDoctorName(doctorId),
                      builder: (context, snapshot) {
                        String drName = "Loading...";
                        if (snapshot.connectionState == ConnectionState.done) {
                          drName = snapshot.data ?? "Unknown";
                        }
                        return Column(
                          children: [
                            _detailRow(Icons.medical_services, "Doctor", "Dr. $drName"),
                            const SizedBox(height: 8),
                            _detailRow(Icons.verified_user, "Doctor ID", doctorId),
                          ],
                        );
                      },
                    ),
                  ],
                ],
              ),
            ),
            const SizedBox(height: 25),

            const Text("AI Diagnosis Findings",
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Color(0xFF1A1C1E))),
            const SizedBox(height: 10),

            // --- FULL REPORT TEXT ---
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: Colors.blueAccent.withOpacity(0.3)),
                boxShadow: [BoxShadow(color: Colors.blue.withOpacity(0.05), blurRadius: 10)],
              ),
              child: Text(
                reportData['reportText'] ?? "No report text available.",
                style: const TextStyle(fontSize: 16, height: 1.6, color: Colors.black87),
              ),
            ),
          ],
        ),
      ),
    );
  }

  // --- UPDATED ROW WIDGET (FIXED OVERFLOW) ---
  Widget _detailRow(IconData icon, String label, String value, {bool isStatus = false}) {
    Color valColor = Colors.black87;
    if (isStatus) {
      valColor = (value.toLowerCase() == 'completed') ? Colors.green : Colors.orange;
    }

    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(color: Colors.grey[100], shape: BoxShape.circle),
            child: Icon(icon, size: 18, color: Colors.grey[700]),
          ),
          const SizedBox(width: 15),

          Text(label, style: const TextStyle(color: Colors.grey, fontWeight: FontWeight.w500)),

          const SizedBox(width: 10),

          // --- FIX: Expanded widget prevents overflow ---
          Expanded(
            child: Text(
              value,
              textAlign: TextAlign.right,
              style: TextStyle(fontWeight: FontWeight.bold, color: valColor, fontSize: 15),
            ),
          ),
        ],
      ),
    );
  }
}